name: turnos_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸŒ LocalizaciÃ³n (usa intl 0.19.0 por pin del SDK)
  flutter_localizations:
    sdk: flutter

  # ðŸ“¦ Dependencias
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
